[book]
title = "dboxide"
authors = ["Huy-DNA"]
language = "en"
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.cmdrun]
command = "mdbook-cmdrun"
renderer = ["html"]

[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/hdnax/dboxide/tree/main/doc"
edit-url-template = "https://github.com/hdnax/dboxide/tree/main/doc"
hash-files = true
site-url = "/dboxide/"
default-theme = "light"
preferred-dark-theme = "navy"
additional-js = ["theme/mermaid.min.js", "theme/mermaid-init.js"]
